stages:
  - test
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

test:
  stage: test
  image: logomotion/code-quality
  script: 
    - phpcs --standard=PSR2 ./src
    - security-checker security:check
    - phpcpd src
    - phpmd src text unusedcode
deploy_staging:
  stage: deploy
  image: php:7-cli-alpine
  before_script:
    - apk add --update git openssh-client
    - mkdir -p ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
  environment:
    name: staging
    url: https://staging.crij
  script:
        - curl -L https://deployer.org/releases/v6.4.3/deployer.phar > /usr/local/bin/deployer && chmod +x /usr/local/bin/deployer
        - deployer -f=deploy/deploy.php deploy
