version: '3'
 
services:
    apache:
        container_name: ${COMPOSE_PROJECT_NAME}_apache_con
        image: logomotion/httpd
        volumes:
            - ./var/logs/apache:/var/log/apache
            - .:/home/wwwroot
        ports:
            - ${APACHE_EXPOSED_PORT}:80
        environment:
            SERVER_HOST_NAME: ${SERVER_HOST_NAME}
    db:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql_con
        image: mysql:5.6
        volumes:
            - ./var/logs/mysql:/var/log/mysql
            - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
    php:
        container_name: ${COMPOSE_PROJECT_NAME}_php_con
        image: logomotion/php:7.2
        working_dir: /home/wwwroot
        volumes:
            - .:/home/wwwroot
            - ./var/logs/php:/usr/local/etc/logs
            - ./var/cache/composer:/var/www/.composer/cache
        links:
          - db:db
        environment:
            ENV: ${ENV}
        user: ${LOCAL_USER}
    phpmyadmin:
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin_con
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - ${PHPMYADMIN_EXPOSED_PORT}:80
    node:
        container_name: ${COMPOSE_PROJECT_NAME}_node_con
        image: node:10.15.1-slim