POST http://127.0.0.1/api/users
Content-Type: application/json
Accept: */*

{
  "email": "superadmin@fixt.com",
  "plainPassword": "admin",
  "gender": "male",
  "name": "Marcel",
  "lastName": "Proust",
  "address": "5 rue de la Trémouille",
  "zipcode": "21000",
  "city": "Dijon",
  "birthdate": "2000-01-01T00:00:00+01:00"
}
###
PATCH http://127.0.0.1/api/user
Content-Type: application/json
Accept: */*

{
  "email": "superadmin@fixt.com",
  "plainPassword": "admin",
  "gender": "male",
  "name": "Marcel",
  "lastName": "Proust",
  "address": "5 rue de la Trémouille",
  "zipcode": "21000",
  "city": "Dijon",
  "birthdate": "2000-01-01T00:00:00+01:00"
}
###
GET http://127.0.0.1/api/user
Content-Type: application/json
Accept: */*