<?php

namespace AppBundle\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\User;
use Pagerfanta\Pagerfanta;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends AbstractRepository implements UserLoaderInterface
{
    /**
     * @var EntityRepository
     */
    private $repository;
    
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->repository = $entityManager->getRepository(User::class);
    }

    public function loadUserByUsername($usernameOrEmail)
    {
        return $this->createQueryBuilder('u')
            ->where('u.username = :query OR u.email = :query')
            ->setParameter('query', $usernameOrEmail)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * Find User by id
     *
     * @param int $id
     * @return Section
     */
    public function find($id)
    {
        $qb = $this->repository->createQueryBuilder('s')
        ->select('s')
        ->where('s.id = :id')
        ->setParameter('id', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }

    /**
     * Find User by Email
     *
     * @param int $email
     * @return Section
     */
    public function findByEmail($email)
    {
        $qb = $this->repository->createQueryBuilder('s')
        ->select('s')
        ->where('s.email = :email')
        ->setParameter('email', $email);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
