category:
  type: rest
  resource: AppBundle\Controller\CategoryController
content:
  type: rest
  resource: AppBundle\Controller\ContentController
section:
  type: rest
  resource: AppBundle\Controller\SectionController
user:
  type: rest
  resource: AppBundle\Controller\UserController
security:
  type: rest
  resource: AppBundle\Controller\SecurityController