parameters:
  entityField:
    organism:
      name: name: 
      initials: initials
      name2: name2
      instGroup: instGroup
      address: address
      address2: address2
      postalBox: postalBox
      poBox: poBox
      zipCode: zipCode
      city: city
      OFZipCode: OFZipCode
      OFCity: OFCity
      cedex: cedex
      phone: phone
      phone2: phone2
      fax: fax
      email: email
      url: url
      department: department
      academy: academy
      region: region
      country: country
      recAdress: recAdress
      openHours: openHours
      missions: missions
      type: type
      netName: netName
      netDescription: netDescription
      agreemment: agreemment
      skills: skills
      zone: zone
      description: description
      roles: roles
      longitude: longitude
      latitude: latitude
    activity:
      aidname: aidname
      description: description
      degreeType: degreeType
      trainingName: trainingName
      degreeOptions: degreeOptions
      degree: degree
      trainingMode: trainingMode
      recruitMode: recruitMode
      benefitType: benefitType
      LessonLevel: LessonLevel
      audienceType: audienceType
      specificAudience: specificAudience
      conditions: conditions
      serviceMission: serviceMission
      publicInfo: publicInfo
      recMode: recMode
      destinations: destinations
      period: period
      cost: cost
      salary: salary
      serviceName: serviceName
      address: address
      address2: address2
      zipCode: zipCode
      city: city
      phone: phone
      fax: fax
      email: email
      aidNature: aidNature
      regLocation: regLocation
      comment: comment
      contact: contact
      trainingDomain: trainingDomain
      partnership: partnership
      activityDomain: activityDomain