security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '%admin_password%'
                        roles: 'ROLE_SUPER_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/api
            provider: in_memory
            json_login:
                check_path: /api/login
                username_path: username
                password_path: password