#!/bin/sh
set -e

docker run --rm -v $PWD:/code:ro logomotion/code-quality phpcs --standard=Symfony ./src
docker run --rm -v $PWD:/code:ro logomotion/code-quality security-checker security:check composer.lock
docker run --rm -v $PWD:/code:ro logomotion/code-quality phpcpd src