#!/bin/sh
set -e

# Symfony's coding standards tests
docker run --rm -v $PWD:/code:ro logomotion/code-quality phpcs --standard=Symfony ./src &&

# php security checks
docker run --rm -v $PWD:/code:ro logomotion/code-quality security-checker security:check composer.lock &&

# php copy paste checks
docker run --rm -v $PWD:/code:ro logomotion/code-quality phpcpd src &&

# javascript's standard checks
docker run --rm -v $PWD:/code:ro logomotion/code-quality standard "assets/js/**/*.js"